import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { prisma } from '@/lib/db';
import { logger } from '@/lib/logger';
import { Prisma } from '@prisma/client';

// GET - Export containers as Excel-compatible CSV
export async function GET(request: NextRequest) {
  try {
    const session = await auth();
    
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const status = searchParams.get('status');
    const search = searchParams.get('search');

    // Build where clause
    const where: Prisma.ContainerWhereInput = {};

    // Non-admin users can only export containers that contain their shipments
    if (session.user.role !== 'admin') {
      where.shipments = {
        some: {
          userId: session.user.id,
        },
      };
    }

    // Filter by status if provided and not 'all'
    if (status && status !== 'all') {
      where.status = status as any;
    }

    // Filter by search query if provided
    if (search) {
      where.OR = [
        { containerNumber: { contains: search, mode: 'insensitive' } },
        { trackingNumber: { contains: search, mode: 'insensitive' } },
        { vesselName: { contains: search, mode: 'insensitive' } },
        { shippingLine: { contains: search, mode: 'insensitive' } },
        { bookingNumber: { contains: search, mode: 'insensitive' } },
      ];
    }

    // Fetch containers with relations
    const containers = await prisma.container.findMany({
      where,
      include: {
        _count: {
          select: {
            shipments: true,
            expenses: true,
            invoices: true,
            documents: true,
          },
        },
      },
      orderBy: {
        createdAt: 'desc',
      },
    });

    // Generate Excel-compatible CSV with UTF-8 BOM for proper Excel encoding
    const csvRows: string[] = [];
    
    // Add BOM for UTF-8
    csvRows.push('\ufeff');
    
    // Header info
    csvRows.push('CONTAINER EXPORT');
    csvRows.push(`Generated By:,${session.user.name || session.user.email}`);
    csvRows.push(`Date:,${new Date().toLocaleString()}`);
    csvRows.push(`Total Records:,${containers.length}`);
    if (status && status !== 'all') csvRows.push(`Status Filter:,${status}`);
    if (search) csvRows.push(`Search Query:,${search}`);
    csvRows.push('');

    // Column Headers
    csvRows.push([
      'Container Number',
      'Status',
      'Tracking Number',
      'Booking Number',
      'Shipping Line',
      'Vessel / Voyage',
      'Loading Port',
      'Destination Port',
      'Departure Date',
      'Arrival Date',
      'Capacity',
      'Vehicle Count',
      'Progress',
      'Notes',
    ].join(','));

    // Data rows
    for (const container of containers) {
      const departureDate = container.departureDate 
        ? new Date(container.departureDate).toLocaleDateString() 
        : '';
        
      const arrivalDate = container.actualArrival 
        ? new Date(container.actualArrival).toLocaleDateString() 
        : (container.estimatedArrival ? `ETA: ${new Date(container.estimatedArrival).toLocaleDateString()}` : '');

      const vesselInfo = [container.vesselName, container.voyageNumber]
        .filter(Boolean)
        .join(' / ');

      const capacity = `${container.currentCount}/${container.maxCapacity}`;
      const progressPercent = `${container.progress}%`;

      csvRows.push([
        container.containerNumber,
        container.status,
        container.trackingNumber || '',
        container.bookingNumber || '',
        `"${(container.shippingLine || '').replace(/"/g, '""')}"`,
        `"${vesselInfo}"`,
        container.loadingPort || '',
        container.destinationPort || '',
        departureDate,
        arrivalDate,
        capacity,
        container._count.shipments.toString(),
        progressPercent,
        container.notes ? `"${container.notes.replace(/"/g, '""')}"` : '',
      ].join(','));
    }

    // Add summary
    csvRows.push('');
    csvRows.push(`Total Containers:,${containers.length}`);

    const csvContent = csvRows.join('\n');

    // Return Excel-compatible CSV file
    return new NextResponse(csvContent, {
      headers: {
        'Content-Type': 'text/csv; charset=utf-8',
        'Content-Disposition': `attachment; filename="containers-${Date.now()}.csv"`,
      },
    });
  } catch (error) {
    logger.error('Error exporting containers:', error);
    return NextResponse.json(
      { error: 'Failed to export containers' },
      { status: 500 }
    );
  }
}